# Análise da Motivação dos Alunos de Engenharia da Computação da Universidade Estadual do Maranhão (UEMA)

Análise exploratória dos dados da pesquisa sobre
a participação em laboratórios/projetos e motivação
dos alunos de Engenharia da Computação.

Dados:
- alunos_geral.csv (alunos em geral, 2025)
- bolsistas.csv (participantes de laboratório e projeto, 2025)
- nova_pesquisa.csv (formulário unificado, 2026)

Objetivo:
Explorar, descrever e comparar percepções de alunos
participantes e não participantes de atividades extracurriculares.

Link repositório Github: https://github.com/Gabriel-c0Nsp/analise-motivacao

## Dependências

In [1]:
%load_ext autoreload
%autoreload 2

from IPython.display import display

from survey import (
    compare_freq,
    compare_items,
    crosstab_counts,
    crosstab_rowperc,
    freq_table,
    load_all,
)

## Carga dos formulários

A carga converte cada resposta para o valor numérico da escala e informa
quantas respostas e variáveis cada formulário tem, além de qualquer valor que
não corresponda à escala declarada.

In [2]:
datasets = load_all()

students_2025_06 = datasets["students_2025_06"]
researchers_2025_06 = datasets["researchers_2025_06"]
students_researchers_2026_04 = datasets["students_researchers_2026_04"]

students_2025_06: 29 respostas, 19 variáveis
researchers_2025_06: 25 respostas, 17 variáveis
students_researchers_2026_04: 39 respostas, 28 variáveis

## Cruzamentos entre variáveis

Cada cruzamento mostra primeiro a distribuição de cada uma das duas variáveis
isoladamente e depois o cruzamento entre elas, em contagens e em percentual por
linha.

### Alunos em geral (2025)

#### participates_lab × lab_helps

In [3]:
display(freq_table(students_2025_06, "participates_lab"))
display(freq_table(students_2025_06, "lab_helps"))

display(crosstab_counts(students_2025_06, "participates_lab", "lab_helps"))
display(crosstab_rowperc(students_2025_06, "participates_lab", "lab_helps"))

                  count  percent
participates_lab
Não                  18     62.1
Sim                  11     37.9

                           count  percent
lab_helps
Discordo totalmente            1      3.4
Discordo parcialmente          1      3.4
Nem concordo nem discordo      2      6.9
Concordo parcialmente         12     41.4
Concordo totalmente           13     44.8

lab_helps         1  2  3  4  5
participates_lab
0                 1  1  2  5  9
1                 0  0  0  7  4

lab_helps           1    2     3     4     5
participates_lab
0                 5.6  5.6  11.1  27.8  50.0
1                 0.0  0.0   0.0  63.6  36.4

#### change_major × financial_impact

In [4]:
display(freq_table(students_2025_06, "financial_impact"))
display(freq_table(students_2025_06, "change_major"))

display(crosstab_counts(students_2025_06, "change_major", "financial_impact"))
display(crosstab_rowperc(students_2025_06, "change_major", "financial_impact"))

                           count  percent
financial_impact
Discordo totalmente            9     31.0
Discordo parcialmente          6     20.7
Nem concordo nem discordo      7     24.1
Concordo parcialmente          4     13.8
Concordo totalmente            3     10.3

              count  percent
change_major
Não              18     62.1
Sim              11     37.9

financial_impact  1  2  3  4  5
change_major
0                 3  5  6  2  2
1                 6  1  1  2  1

financial_impact     1     2     3     4     5
change_major
0                 16.7  27.8  33.3  11.1  11.1
1                 54.5   9.1   9.1  18.2   9.1

#### financial_hardship × dropped_courses

In [5]:
display(freq_table(students_2025_06, "financial_hardship"))
display(freq_table(students_2025_06, "dropped_courses"))

display(crosstab_counts(students_2025_06, "financial_hardship", "dropped_courses"))
display(crosstab_rowperc(students_2025_06, "financial_hardship", "dropped_courses"))

                           count  percent
financial_hardship
Discordo totalmente           12     41.4
Discordo parcialmente          5     17.2
Nem concordo nem discordo      7     24.1
Concordo parcialmente          5     17.2

                 count  percent
dropped_courses
Não                 15     51.7
Sim                 14     48.3

dropped_courses     0  1
financial_hardship
1                   8  4
2                   0  5
3                   6  1
4                   1  4

dropped_courses        0      1
financial_hardship
1                   66.7   33.3
2                    0.0  100.0
3                   85.7   14.3
4                   20.0   80.0

#### change_major × welcomed_by_faculty

In [6]:
display(freq_table(students_2025_06, "change_major"))
display(freq_table(students_2025_06, "welcomed_by_faculty"))

display(crosstab_counts(students_2025_06, "change_major", "welcomed_by_faculty"))
display(crosstab_rowperc(students_2025_06, "change_major", "welcomed_by_faculty"))

              count  percent
change_major
Não              18     62.1
Sim              11     37.9

                           count  percent
welcomed_by_faculty
Discordo parcialmente          4     13.8
Nem concordo nem discordo     10     34.5
Concordo parcialmente         11     37.9
Concordo totalmente            4     13.8

welcomed_by_faculty  2  3  4  5
change_major
0                    2  6  7  3
1                    2  4  4  1

welcomed_by_faculty     2     3     4     5
change_major
0                    11.1  33.3  38.9  16.7
1                    18.2  36.4  36.4   9.1

#### has_scholarship × change_major

In [7]:
display(freq_table(students_2025_06, "has_scholarship"))
display(freq_table(students_2025_06, "change_major"))

display(crosstab_counts(students_2025_06, "has_scholarship", "change_major"))
display(crosstab_rowperc(students_2025_06, "has_scholarship", "change_major"))

                 count  percent
has_scholarship
Não                 24     82.8
Sim                  5     17.2

              count  percent
change_major
Não              18     62.1
Sim              11     37.9

change_major      0  1
has_scholarship
0                16  8
1                 2  3

change_major        0     1
has_scholarship
0                66.7  33.3
1                40.0  60.0

#### welcomed_by_faculty × welcoming_environment

In [8]:
display(freq_table(students_2025_06, "welcomed_by_faculty"))
display(freq_table(students_2025_06, "welcoming_environment"))

display(crosstab_counts(students_2025_06, "welcomed_by_faculty", "welcoming_environment"))
display(crosstab_rowperc(students_2025_06, "welcomed_by_faculty", "welcoming_environment"))

                           count  percent
welcomed_by_faculty
Discordo parcialmente          4     13.8
Nem concordo nem discordo     10     34.5
Concordo parcialmente         11     37.9
Concordo totalmente            4     13.8

                           count  percent
welcoming_environment
Discordo totalmente            1      3.4
Discordo parcialmente          4     13.8
Nem concordo nem discordo      9     31.0
Concordo parcialmente         10     34.5
Concordo totalmente            5     17.2

welcoming_environment  1  2  3  4  5
welcomed_by_faculty
2                      0  1  1  2  0
3                      1  2  4  3  0
4                      0  0  3  5  3
5                      0  1  1  0  2

welcoming_environment     1     2     3     4     5
welcomed_by_faculty
2                       0.0  25.0  25.0  50.0   0.0
3                      10.0  20.0  40.0  30.0   0.0
4                       0.0   0.0  27.3  45.5  27.3
5                       0.0  25.0  25.0   0.0  50.0

#### works × keeps_up

In [9]:
display(freq_table(students_2025_06, "works"))
display(freq_table(students_2025_06, "keeps_up"))

display(crosstab_counts(students_2025_06, "works", "keeps_up"))
display(crosstab_rowperc(students_2025_06, "works", "keeps_up"))

       count  percent
works
Não       20     69.0
Sim        9     31.0

                           count  percent
keeps_up
Discordo totalmente            5     17.2
Discordo parcialmente          5     17.2
Nem concordo nem discordo      6     20.7
Concordo parcialmente         11     37.9
Concordo totalmente            2      6.9

keeps_up  1  2  3  4  5
works
0         2  3  5  8  2
1         3  2  1  3  0

keeps_up     1     2     3     4     5
works
0         10.0  15.0  25.0  40.0  10.0
1         33.3  22.2  11.1  33.3   0.0

#### works × change_major

In [10]:
display(freq_table(students_2025_06, "works"))
display(freq_table(students_2025_06, "change_major"))

display(crosstab_counts(students_2025_06, "works", "change_major"))
display(crosstab_rowperc(students_2025_06, "works", "change_major"))

       count  percent
works
Não       20     69.0
Sim        9     31.0

              count  percent
change_major
Não              18     62.1
Sim              11     37.9

change_major   0  1
works
0             13  7
1              5  4

change_major     0     1
works
0             65.0  35.0
1             55.6  44.4

#### works × dropped_courses

In [11]:
display(freq_table(students_2025_06, "works"))
display(freq_table(students_2025_06, "dropped_courses"))

display(crosstab_counts(students_2025_06, "works", "dropped_courses"))
display(crosstab_rowperc(students_2025_06, "works", "dropped_courses"))

       count  percent
works
Não       20     69.0
Sim        9     31.0

                 count  percent
dropped_courses
Não                 15     51.7
Sim                 14     48.3

dropped_courses   0  1
works
0                14  6
1                 1  8

dropped_courses     0     1
works
0                70.0  30.0
1                11.1  88.9

#### participates_lab × change_major

In [12]:
display(freq_table(students_2025_06, "participates_lab"))
display(freq_table(students_2025_06, "change_major"))

display(crosstab_counts(students_2025_06, "participates_lab", "change_major"))
display(crosstab_rowperc(students_2025_06, "participates_lab", "change_major"))

                  count  percent
participates_lab
Não                  18     62.1
Sim                  11     37.9

              count  percent
change_major
Não              18     62.1
Sim              11     37.9

change_major       0  1
participates_lab
0                 11  7
1                  7  4

change_major         0     1
participates_lab
0                 61.1  38.9
1                 63.6  36.4

#### knows_opportunities × participates_lab

In [13]:
display(freq_table(students_2025_06, "knows_opportunities"))
display(freq_table(students_2025_06, "participates_lab"))

display(crosstab_counts(students_2025_06, "knows_opportunities", "participates_lab"))
display(crosstab_rowperc(students_2025_06, "knows_opportunities", "participates_lab"))

                     count  percent
knows_opportunities
Não                     11     37.9
Sim                     18     62.1

                  count  percent
participates_lab
Não                  18     62.1
Sim                  11     37.9

participates_lab      0  1
knows_opportunities
0                     7  4
1                    11  7

participates_lab        0     1
knows_opportunities
0                    63.6  36.4
1                    61.1  38.9

#### meets_requirements × participates_lab

In [14]:
display(freq_table(students_2025_06, "meets_requirements"))
display(freq_table(students_2025_06, "participates_lab"))

display(crosstab_counts(students_2025_06, "meets_requirements", "participates_lab"))
display(crosstab_rowperc(students_2025_06, "meets_requirements", "participates_lab"))

                    count  percent
meets_requirements
Não                    16     55.2
Sim                    13     44.8

                  count  percent
participates_lab
Não                  18     62.1
Sim                  11     37.9

participates_lab     0  1
meets_requirements
0                   12  4
1                    6  7

participates_lab       0     1
meets_requirements
0                   75.0  25.0
1                   46.2  53.8

#### school_base × keeps_up

In [15]:
display(freq_table(students_2025_06, "school_base"))
display(freq_table(students_2025_06, "keeps_up"))

display(crosstab_counts(students_2025_06, "school_base", "keeps_up"))
display(crosstab_rowperc(students_2025_06, "school_base", "keeps_up"))

                           count  percent
school_base
Discordo totalmente            4     13.8
Discordo parcialmente          2      6.9
Nem concordo nem discordo      6     20.7
Concordo parcialmente          9     31.0
Concordo totalmente            8     27.6

                           count  percent
keeps_up
Discordo totalmente            5     17.2
Discordo parcialmente          5     17.2
Nem concordo nem discordo      6     20.7
Concordo parcialmente         11     37.9
Concordo totalmente            2      6.9

keeps_up     1  2  3  4  5
school_base
1            1  0  3  0  0
2            0  1  0  1  0
3            2  1  1  2  0
4            1  2  2  3  1
5            1  1  0  5  1

keeps_up        1     2     3     4     5
school_base
1            25.0   0.0  75.0   0.0   0.0
2             0.0  50.0   0.0  50.0   0.0
3            33.3  16.7  16.7  33.3   0.0
4            11.1  22.2  22.2  33.3  11.1
5            12.5  12.5   0.0  62.5  12.5

### Participantes de laboratório e projeto (2025)

#### considered_quitting × lacks_time

In [16]:
display(freq_table(researchers_2025_06, "lacks_time"))
display(freq_table(researchers_2025_06, "considered_quitting"))

display(crosstab_counts(researchers_2025_06, "considered_quitting", "lacks_time"))
display(crosstab_rowperc(researchers_2025_06, "considered_quitting", "lacks_time"))

                           count  percent
lacks_time
Discordo totalmente            1      4.0
Discordo parcialmente          7     28.0
Nem concordo nem discordo      3     12.0
Concordo parcialmente         13     52.0
Concordo totalmente            1      4.0

                     count  percent
considered_quitting
Não                     13     52.0
Sim                     12     48.0

lacks_time           1  2  3  4  5
considered_quitting
0                    1  5  1  6  0
1                    0  2  2  7  1

lacks_time             1     2     3     4    5
considered_quitting
0                    7.7  38.5   7.7  46.2  0.0
1                    0.0  16.7  16.7  58.3  8.3

#### recommended_to_peers × good_supervision

In [17]:
display(freq_table(researchers_2025_06, "good_supervision"))
display(freq_table(researchers_2025_06, "recommended_to_peers"))

display(crosstab_counts(researchers_2025_06, "recommended_to_peers", "good_supervision"))
display(crosstab_rowperc(researchers_2025_06, "recommended_to_peers", "good_supervision"))

                           count  percent
good_supervision
Discordo parcialmente          2      8.0
Nem concordo nem discordo      1      4.0
Concordo parcialmente          6     24.0
Concordo totalmente           16     64.0

                      count  percent
recommended_to_peers
Não                       4     16.0
Sim                      21     84.0

good_supervision      2  3  4   5
recommended_to_peers
0                     1  0  2   1
1                     1  1  4  15

good_supervision         2    3     4     5
recommended_to_peers
0                     25.0  0.0  50.0  25.0
1                      4.8  4.8  19.0  71.4

#### recommended_to_peers × recognition_motivates

In [18]:
display(freq_table(researchers_2025_06, "recommended_to_peers"))
display(freq_table(researchers_2025_06, "recognition_motivates"))

display(crosstab_counts(researchers_2025_06, "recommended_to_peers", "recognition_motivates"))
display(crosstab_rowperc(researchers_2025_06, "recommended_to_peers", "recognition_motivates"))

                      count  percent
recommended_to_peers
Não                       4     16.0
Sim                      21     84.0

                           count  percent
recognition_motivates
Discordo parcialmente          1      4.0
Nem concordo nem discordo      3     12.0
Concordo parcialmente          7     28.0
Concordo totalmente           14     56.0

recognition_motivates  2  3  4   5
recommended_to_peers
0                      0  2  1   1
1                      1  1  6  13

recognition_motivates    2     3     4     5
recommended_to_peers
0                      0.0  50.0  25.0  25.0
1                      4.8   4.8  28.6  61.9

#### activity_role × considered_quitting

In [19]:
display(freq_table(researchers_2025_06, "activity_role"))
display(freq_table(researchers_2025_06, "considered_quitting"))

display(crosstab_counts(researchers_2025_06, "activity_role", "considered_quitting"))
display(crosstab_rowperc(researchers_2025_06, "activity_role", "considered_quitting"))

                                 count  percent
activity_role
Bolsista                            16     64.0
Voluntário                           6     24.0
Não se aplica à minha atividade      3     12.0

                     count  percent
considered_quitting
Não                     13     52.0
Sim                     12     48.0

considered_quitting               0  1
activity_role
Bolsista                         11  5
Não se aplica à minha atividade   1  2
Voluntário                        1  5

considered_quitting                 0     1
activity_role
Bolsista                         68.8  31.2
Não se aplica à minha atividade  33.3  66.7
Voluntário                       16.7  83.3

#### good_supervision × considered_quitting

In [20]:
display(freq_table(researchers_2025_06, "good_supervision"))
display(freq_table(researchers_2025_06, "considered_quitting"))

display(crosstab_counts(researchers_2025_06, "good_supervision", "considered_quitting"))
display(crosstab_rowperc(researchers_2025_06, "good_supervision", "considered_quitting"))

                           count  percent
good_supervision
Discordo parcialmente          2      8.0
Nem concordo nem discordo      1      4.0
Concordo parcialmente          6     24.0
Concordo totalmente           16     64.0

                     count  percent
considered_quitting
Não                     13     52.0
Sim                     12     48.0

considered_quitting   0  1
good_supervision
2                     1  1
3                     0  1
4                     2  4
5                    10  6

considered_quitting     0      1
good_supervision
2                    50.0   50.0
3                     0.0  100.0
4                    33.3   66.7
5                    62.5   37.5

#### stipend_enough × considered_quitting

In [21]:
display(freq_table(researchers_2025_06, "stipend_enough"))
display(freq_table(researchers_2025_06, "considered_quitting"))

display(crosstab_counts(researchers_2025_06, "stipend_enough", "considered_quitting"))
display(crosstab_rowperc(researchers_2025_06, "stipend_enough", "considered_quitting"))

                           count  percent
stipend_enough
Discordo totalmente            3     12.0
Discordo parcialmente          4     16.0
Nem concordo nem discordo      8     32.0
Concordo parcialmente          5     20.0
Concordo totalmente            5     20.0

                     count  percent
considered_quitting
Não                     13     52.0
Sim                     12     48.0

considered_quitting  0  1
stipend_enough
1                    0  3
2                    1  3
3                    4  4
4                    4  1
5                    4  1

considered_quitting     0      1
stipend_enough
1                     0.0  100.0
2                    25.0   75.0
3                    50.0   50.0
4                    80.0   20.0
5                    80.0   20.0

## Ponte entre os formulários

Os dois formulários de 2025 perguntam sobre o efeito da participação em
laboratório, mas não são o mesmo item. Entre os alunos em geral, `lab_helps` é
respondido também por quem nunca participou, então mede expectativa. Entre os
bolsistas, `lab_helped` é respondido por quem participa, então mede
experiência. A comparação abaixo declara essa diferença e imprime o texto das
duas perguntas antes de mostrar os percentuais.

Em seguida vem a comparação de `lab_helps` entre 2025 e 2026, que é limpa por
usar exatamente a mesma pergunta nos dois lados.

In [22]:
display(compare_items([
    ("students_2025_06", "lab_helps"),
    ("researchers_2025_06", "lab_helped"),
]))

display(compare_freq([students_2025_06, students_researchers_2026_04], "lab_helps"))

Comparando itens de perguntas diferentes:
  Alunos 2025 (lab_helps): A participação em laboratórios ou projetos de pesquisa ajuda (ou ajudaria) a compreender melhor os conteúdos das disciplinas.
  Bolsistas 2025 (lab_helped): A participação em projetos de pesquisa ou laboratórios ajudou a compreender melhor os conteúdos vistos em sala de aula.
Ressalva sobre lab_helps: Mede expectativa, porque é respondida também por quem nunca participou. Não é o mesmo item que lab_helped, que mede experiência e só existe em 2025.

,Alunos 2025 (lab_helps),Bolsistas 2025 (lab_helped)
Discordo totalmente,3.4,0.0
Discordo parcialmente,3.4,4.0
Nem concordo nem discordo,6.9,16.0
Concordo parcialmente,41.4,36.0
Concordo totalmente,44.8,44.0

Ressalva sobre lab_helps: Mede expectativa, porque é respondida também por quem nunca participou. Não é o mesmo item que lab_helped, que mede experiência e só existe em 2025.

                           Alunos 2025  Pesquisa 2026
lab_helps
Discordo totalmente                3.4            0.0
Discordo parcialmente              3.4            2.6
Nem concordo nem discordo          6.9           10.3
Concordo parcialmente             41.4           25.6
Concordo totalmente               44.8           61.5