# Análise da Motivação dos Alunos de Engenharia da Computação da Universidade Estadual do Maranhão (UEMA)

Análise exploratória dos dados da pesquisa sobre
a participação em laboratórios/projetos e motivação
dos alunos de Engenharia da Computação.

Dados:
- alunos_geral.csv
- bolsistas.csv

Objetivo:
Explorar, descrever e comparar percepções de alunos
participantes e não participantes de atividades extracurriculares.

Link repositório Github: https://github.com/Gabriel-c0Nsp/analise-motivacao

### Dependências

In [105]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display

### Leitura dos CSVs

In [106]:
alunos = pd.read_csv("dados/alunos_geral.csv")
pesquisadores = pd.read_csv("dados/bolsistas.csv")

### Remoção de espaços em branco

In [107]:
alunos.columns = alunos.columns.str.strip()
pesquisadores.columns = pesquisadores.columns.str.strip()

### Funções auxiliares

### Setup

In [108]:
LIKERT_5 = {
    "Discordo totalmente": 1,
    "Discordo parcialmente": 2,
    "Nem concordo nem discordo": 3,
    "Neutro": 3,
    "Concordo parcialmente": 4,
    "Concordo totalmente": 5,
}

LIKERT_ORDER = [
    "Discordo totalmente",
    "Discordo parcialmente",
    "Nem concordo nem discordo",
    "Neutro",
    "Concordo parcialmente",
    "Concordo totalmente",
]

SIM_NAO = {"Não": 0, "Sim": 1}

COL = {
    # alunos (geral)
    "al_faixa_etaria": "Qual sua faixa etária?",
    "al_boa_base": "Recebi uma boa base de aprendizado durante os anos escolares.",
    "al_acolh_prof": "Me sinto acolhido(a) por professores e monitores quando tenho dúvidas.",
    "al_participa_lab": "Participa de algum laboratório ou projeto de pesquisa da universidade?",
    "al_participa_extra": "Participa de atividades extra curriculares, como eventos e esportes na faculdade?",
    "al_dif_fin": "Atualmente enfrento dificuldades financeiras.",
    "al_meio_acolhedor": "Considero o meio acadêmico do qual faço parte acolhedor.",
    "al_bolsa": "Recebe alguma bolsa/auxilio da faculdade?",
    "al_trancou": "Já trancou cadeiras por não acompanhar o conteúdo?",
    "al_trocar_curso": "Considera trocar de curso?",
    "al_trabalha": "Trabalha no contraturno das aulas?",
    "al_acompanha": "Consigo acompanhar a maioria dos conteúdos ministrados em sala de aula atualmente.",
    "al_fin_afeta": "As dificuldades financeiras afetam minha vida acadêmica.",
    "al_lab_ajuda": "A participação em laboratórios ou projetos de pesquisa ajuda (ou ajudaria) a compreender melhor os conteúdos das disciplinas.",
    "al_conhece_oport": "Você conhece as oportunidades de iniciação científica, monitoria ou laboratórios oferecidas pela universidade?",
    "al_atende_req": "Você atende aos requisitos necessários para participar de projetos de iniciação científica (CR acima de 7.0 e disciplinas pagas em caso de reprovação)?",
    "al_prep_mercado": "Me sinto preparado(a) para atuar no mercado de trabalho com o que aprendo na graduação.",
    "al_grade": "Como você avalia a grade currilar vigente?",
    "al_infraestrutura": "Como você avalia a infraestrutura do prédio de computação?",

    # pesquisadores
    "pes_faixa_etaria": "Qual sua faixa etária?",
    "pes_tipo_atividade": "Qual o tipo de atividade que você realiza atualmente?",
    "pes_participacao": "Qual a sua participação em relação às atividades citadas acima?",
    "pes_carga_horaria": "Como você avalia a carga horária da atividade em relação à sua rotina de estudos?",
    "pes_lab_ajuda": "A participação em projetos de pesquisa ou laboratórios ajudou a compreender melhor os conteúdos vistos em sala de aula.",
    "pes_contribui_formacao": "A atividade que desenvolvo no projeto contribui para a minha formação profissional.",
    "pes_pensou_desistir": "Já pensou em desistir da atividade de laboratório ou extensão por excesso de demandas acadêmicas?",
    "pes_bolsa_suficiente": "A bolsa que recebo é suficiente para cobrir minhas principais despesas acadêmicas.",
    "pes_orientacao": "Recebo orientação adequada do meu professor orientador.",
    "pes_falta_tempo": "Sinto que não tenho tempo suficiente para conciliar as disciplinas regulares, a atividade no laboratório/projeto e minha vida pessoal.",
    "pes_producao": "Sua participação no projeto já resultou em alguma produção acadêmica? (ex: artigo, resumo, apresentação em evento, etc.).",
    "pes_recomendaria": "Você já recomendou a colegas a participação no laboratório ou projeto?",
    "pes_mais_de_um": "Você participa de mais de um projeto/laboratório ao mesmo tempo?",
    "pes_habilidades": "A participação no laboratório/projeto contribui para o desenvolvimento das minhas habilidades interpessoais (como comunicação, trabalho em equipe e liderança).",
    "pes_reconhecimento_motiv": "O reconhecimento (formal ou informal) pelo meu trabalho no laboratório/projeto contribuiu para minha motivação no curso.",
    "pes_reduz_evasao": "Acredito que as atividades extracurriculares contribuem para reduzir a evasão de alunos do curso.",
}

In [109]:
def clean_text(x):
    """Padroniza strings: remove espaços extras e converte para string quando possível."""
    if pd.isna(x):
        return x
    return str(x).strip()

def freq_table(df, col, dropna=False, sort_index=True, likert_order=True):    
    """
    Retorna uma tabela com contagem e percentual da coluna.
    - dropna=False mostra NaN
    """
    s = df[col].map(clean_text)
    counts = s.value_counts(dropna=dropna)
    if sort_index:
        counts = counts.sort_index()
    perc = (counts / counts.sum() * 100).round(1)
    return pd.DataFrame({"count": counts, "percent": perc})

## Uso ##
# col = "A participação em projetos de pesquisa ou laboratórios ajudou a compreender melhor os conteúdos vistos em sala de aula."
# freq_table(participantes, col)

def to_likert_num(df, col, new_col):
    """
    Cria new_col com valores 1..5 a partir de uma coluna Likert.
    Também retorna a contagem de NaN para você checar se algo não foi mapeado.
    """
    s = df[col].map(clean_text)
    df[new_col] = s.map(LIKERT_5)
    nan_count = df[new_col].isna().sum()
    return nan_count

## Uso ##
# col = "A participação em projetos de pesquisa ou laboratórios ajudou a compreender melhor os conteúdos vistos em sala de aula."
# nan = to_likert_num(participantes, col, "ajuda_compreender_num")
# nan

def to_bin_num(df, col, new_col):
    s = df[col].map(clean_text)
    df[new_col] = s.map(SIM_NAO)
    nan_count = df[new_col].isna().sum()
    return nan_count

## Uso ##
# col = "Participa de algum laboratório ou projeto de pesquisa da universidade?"
# nan = to_bin_num(alunos, col, "participa_lab")
# nan

def plot_likert_bar(df, col_num, title):
    counts = df[col_num].value_counts().sort_index()
    counts.plot(kind="bar")
    plt.xlabel("Likert (1=Discordo total, 5=Concordo total)")
    plt.ylabel("Número de respostas")
    plt.title(title)
    plt.show()

## Uso ##
# plot_likert_bar(participantes, "ajuda_compreender_num", "Participantes: ajuda a compreender conteúdos")

def crosstab_counts(df, a, b):
    """Tabela de contagens: A x B."""
    return pd.crosstab(df[a], df[b])

def crosstab_rowperc(df, a, b):
    """Tabela de percentuais por linha (cada linha soma 100%)."""
    tab = pd.crosstab(df[a], df[b])
    return (tab.div(tab.sum(axis=1), axis=0) * 100).round(1)

## Uso ##
# 1) garantir colunas numéricas
# to_bin_num(alunos, "Participa de algum laboratório ou projeto de pesquisa da universidade?", "participa_lab")
# to_likert_num(alunos, "A participação em laboratórios ou projetos de pesquisa ajuda (ou ajudaria) a compreender melhor os conteúdos das disciplinas.", "lab_ajuda_num")

# 2) cruzar
# crosstab_counts(alunos, "participa_lab", "lab_ajuda_num")
# crosstab_rowperc(alunos, "participa_lab", "lab_ajuda_num")

# Diferentes testes e análises exploratórias a partir daqui (temporário)

### Criação de colunas para análise com base no tipo de dado (binário ou Likert)

In [110]:
# ── ALUNOS: binárias ──────────────────────────────────────────────
to_bin_num(alunos, COL["al_participa_lab"],   "participa_lab")
to_bin_num(alunos, COL["al_participa_extra"], "participa_extra")
to_bin_num(alunos, COL["al_bolsa"],           "bolsa")
to_bin_num(alunos, COL["al_trancou"],         "trancou")
to_bin_num(alunos, COL["al_trocar_curso"],    "trocar_curso")
to_bin_num(alunos, COL["al_trabalha"],        "trabalha")
to_bin_num(alunos, COL["al_conhece_oport"],   "conhece_oport")
to_bin_num(alunos, COL["al_atende_req"],      "atende_req")

# ── ALUNOS: Likert ────────────────────────────────────────────────
to_likert_num(alunos, COL["al_boa_base"],        "boa_base_num")
to_likert_num(alunos, COL["al_acolh_prof"],      "acolh_prof_num")
to_likert_num(alunos, COL["al_dif_fin"],         "dif_fin_num")
to_likert_num(alunos, COL["al_meio_acolhedor"],  "meio_acolhedor_num")
to_likert_num(alunos, COL["al_acompanha"],       "acompanha_num")
to_likert_num(alunos, COL["al_fin_afeta"],       "fin_afeta_num")
to_likert_num(alunos, COL["al_lab_ajuda"],       "lab_ajuda_num")
to_likert_num(alunos, COL["al_prep_mercado"],    "prep_mercado_num")

# ── ALUNOS: categóricas (sem mapeamento fixo) ─────────────────────
alunos["faixa_etaria"]   = alunos[COL["al_faixa_etaria"]].map(clean_text)
alunos["grade"]          = alunos[COL["al_grade"]].map(clean_text)
alunos["infraestrutura"] = alunos[COL["al_infraestrutura"]].map(clean_text)

# ── PESQUISADORES: binárias ───────────────────────────────────────
to_bin_num(pesquisadores, COL["pes_pensou_desistir"], "pensou_desistir")
to_bin_num(pesquisadores, COL["pes_recomendaria"],    "recomendaria")
to_bin_num(pesquisadores, COL["pes_producao"],        "producao")
to_bin_num(pesquisadores, COL["pes_mais_de_um"],      "mais_de_um")

# ── PESQUISADORES: Likert ─────────────────────────────────────────
to_likert_num(pesquisadores, COL["pes_lab_ajuda"],           "lab_ajuda_num")
to_likert_num(pesquisadores, COL["pes_contribui_formacao"],  "contribui_formacao_num")
to_likert_num(pesquisadores, COL["pes_bolsa_suficiente"],    "bolsa_suficiente_num")
to_likert_num(pesquisadores, COL["pes_orientacao"],          "orientacao_num")
to_likert_num(pesquisadores, COL["pes_falta_tempo"],         "falta_tempo_num")
to_likert_num(pesquisadores, COL["pes_habilidades"],         "habilidades_num")
to_likert_num(pesquisadores, COL["pes_reconhecimento_motiv"],"reconhecimento_num")
to_likert_num(pesquisadores, COL["pes_reduz_evasao"],        "reduz_evasao_num")

# ── PESQUISADORES: categóricas (sem mapeamento fixo) ─────────────
pesquisadores["faixa_etaria"]    = pesquisadores[COL["pes_faixa_etaria"]].map(clean_text)
pesquisadores["tipo_atividade"]  = pesquisadores[COL["pes_tipo_atividade"]].map(clean_text)
pesquisadores["participacao"]    = pesquisadores[COL["pes_participacao"]].map(clean_text)
pesquisadores["carga_horaria"]   = pesquisadores[COL["pes_carga_horaria"]].map(clean_text)

#### Alunos: participa_lab × lab_ajuda_num

In [111]:
display(freq_table(alunos, COL["al_participa_lab"]))
display(freq_table(alunos, COL["al_lab_ajuda"]))

display(crosstab_counts(alunos, "participa_lab", "lab_ajuda_num"))
display(crosstab_rowperc(alunos, "participa_lab", "lab_ajuda_num"))

                                                    count  percent
Participa de algum laboratório ou projeto de pe...
Não                                                    18     62.1
Sim                                                    11     37.9

                                                    count  percent
A participação em laboratórios ou projetos de p...
Concordo parcialmente                                  12     41.4
Concordo totalmente                                    13     44.8
Discordo parcialmente                                   1      3.4
Discordo totalmente                                     1      3.4
Nem concordo nem discordo                               2      6.9

lab_ajuda_num  1  2  3  4  5
participa_lab
0              1  1  2  5  9
1              0  0  0  7  4

lab_ajuda_num    1    2     3     4     5
participa_lab
0              5.6  5.6  11.1  27.8  50.0
1              0.0  0.0   0.0  63.6  36.4

#### Alunos: fin_afeta_num × trocar_curso

In [112]:
display(freq_table(alunos, COL["al_fin_afeta"]))
display(freq_table(alunos, COL["al_trocar_curso"]))

display(crosstab_counts(alunos, "trocar_curso", "fin_afeta_num"))
display(crosstab_rowperc(alunos, "trocar_curso", "fin_afeta_num"))

                                                    count  percent
As dificuldades financeiras afetam minha vida a...
Concordo parcialmente                                   4     13.8
Concordo totalmente                                     3     10.3
Discordo parcialmente                                   6     20.7
Discordo totalmente                                     9     31.0
Nem concordo nem discordo                               7     24.1

                            count  percent
Considera trocar de curso?
Não                            18     62.1
Sim                            11     37.9

fin_afeta_num  1  2  3  4  5
trocar_curso
0              3  5  6  2  2
1              6  1  1  2  1

fin_afeta_num     1     2     3     4     5
trocar_curso
0              16.7  27.8  33.3  11.1  11.1
1              54.5   9.1   9.1  18.2   9.1

#### Alunos: dif_fin_num × trancou

In [113]:
display(freq_table(alunos, COL["al_dif_fin"]))
display(freq_table(alunos, COL["al_trancou"]))

display(crosstab_counts(alunos, "dif_fin_num", "trancou"))
display(crosstab_rowperc(alunos, "dif_fin_num", "trancou"))

                                               count  percent
Atualmente enfrento dificuldades financeiras.
Concordo parcialmente                              5     17.2
Discordo parcialmente                              5     17.2
Discordo totalmente                               12     41.4
Nem concordo nem discordo                          7     24.1

                                                    count  percent
Já trancou cadeiras por não acompanhar o conteúdo?
Não                                                    15     51.7
Sim                                                    14     48.3

trancou      0  1
dif_fin_num
1            8  4
2            0  5
3            6  1
4            1  4

trancou         0      1
dif_fin_num
1            66.7   33.3
2             0.0  100.0
3            85.7   14.3
4            20.0   80.0

#### Alunos: acolh_prof_num × trocar_curso

In [114]:
display(freq_table(alunos, COL["al_trocar_curso"]))
display(freq_table(alunos, COL["al_acolh_prof"]))

display(crosstab_counts(alunos, "trocar_curso", "acolh_prof_num"))
display(crosstab_rowperc(alunos, "trocar_curso", "acolh_prof_num"))

                            count  percent
Considera trocar de curso?
Não                            18     62.1
Sim                            11     37.9

                                                    count  percent
Me sinto acolhido(a) por professores e monitore...
Concordo parcialmente                                  11     37.9
Concordo totalmente                                     4     13.8
Discordo parcialmente                                   4     13.8
Nem concordo nem discordo                              10     34.5

acolh_prof_num  2  3  4  5
trocar_curso
0               2  6  7  3
1               2  4  4  1

acolh_prof_num     2     3     4     5
trocar_curso
0               11.1  33.3  38.9  16.7
1               18.2  36.4  36.4   9.1

#### Alunos: bolsa × trocar_curso

In [115]:
display(freq_table(alunos, COL["al_bolsa"]))
display(freq_table(alunos, COL["al_trocar_curso"]))

display(crosstab_counts(alunos, "bolsa", "trocar_curso"))
display(crosstab_rowperc(alunos, "bolsa", "trocar_curso"))

                                           count  percent
Recebe alguma bolsa/auxilio da faculdade?
Não                                           24     82.8
Sim                                            5     17.2

                            count  percent
Considera trocar de curso?
Não                            18     62.1
Sim                            11     37.9

trocar_curso   0  1
bolsa
0             16  8
1              2  3

trocar_curso     0     1
bolsa
0             66.7  33.3
1             40.0  60.0

#### Alunos: acolh_prof_num × meio_acolhedor_num

In [116]:
display(freq_table(alunos, COL["al_acolh_prof"]))
display(freq_table(alunos, COL["al_meio_acolhedor"]))

display(crosstab_counts(alunos, "acolh_prof_num", "meio_acolhedor_num"))
display(crosstab_rowperc(alunos, "acolh_prof_num", "meio_acolhedor_num"))

                                                    count  percent
Me sinto acolhido(a) por professores e monitore...
Concordo parcialmente                                  11     37.9
Concordo totalmente                                     4     13.8
Discordo parcialmente                                   4     13.8
Nem concordo nem discordo                              10     34.5

                                                    count  percent
Considero o meio acadêmico do qual faço parte a...
Concordo parcialmente                                  10     34.5
Concordo totalmente                                     5     17.2
Discordo parcialmente                                   4     13.8
Discordo totalmente                                     1      3.4
Nem concordo nem discordo                               9     31.0

meio_acolhedor_num  1  2  3  4  5
acolh_prof_num
2                   0  1  1  2  0
3                   1  2  4  3  0
4                   0  0  3  5  3
5                   0  1  1  0  2

meio_acolhedor_num     1     2     3     4     5
acolh_prof_num
2                    0.0  25.0  25.0  50.0   0.0
3                   10.0  20.0  40.0  30.0   0.0
4                    0.0   0.0  27.3  45.5  27.3
5                    0.0  25.0  25.0   0.0  50.0

#### Alunos: trabalha × acompanha_num

In [117]:
display(freq_table(alunos, COL["al_trabalha"]))
display(freq_table(alunos, COL["al_acompanha"]))

display(crosstab_counts(alunos, "trabalha", "acompanha_num"))
display(crosstab_rowperc(alunos, "trabalha", "acompanha_num"))

                                    count  percent
Trabalha no contraturno das aulas?
Não                                    20     69.0
Sim                                     9     31.0

                                                    count  percent
Consigo acompanhar a maioria dos conteúdos mini...
Concordo parcialmente                                  11     37.9
Concordo totalmente                                     2      6.9
Discordo parcialmente                                   5     17.2
Discordo totalmente                                     5     17.2
Nem concordo nem discordo                               6     20.7

acompanha_num  1  2  3  4  5
trabalha
0              2  3  5  8  2
1              3  2  1  3  0

acompanha_num     1     2     3     4     5
trabalha
0              10.0  15.0  25.0  40.0  10.0
1              33.3  22.2  11.1  33.3   0.0

#### Alunos: trabalha × trocar_curso

In [118]:
display(freq_table(alunos, COL["al_trabalha"]))
display(freq_table(alunos, COL["al_trocar_curso"]))

display(crosstab_counts(alunos, "trabalha", "trocar_curso"))
display(crosstab_rowperc(alunos, "trabalha", "trocar_curso"))

                                    count  percent
Trabalha no contraturno das aulas?
Não                                    20     69.0
Sim                                     9     31.0

                            count  percent
Considera trocar de curso?
Não                            18     62.1
Sim                            11     37.9

trocar_curso   0  1
trabalha
0             13  7
1              5  4

trocar_curso     0     1
trabalha
0             65.0  35.0
1             55.6  44.4

#### Alunos: trabalha × trancou

In [119]:
display(freq_table(alunos, COL["al_trabalha"]))
display(freq_table(alunos, COL["al_trancou"]))

display(crosstab_counts(alunos, "trabalha", "trancou"))
display(crosstab_rowperc(alunos, "trabalha", "trancou"))

                                    count  percent
Trabalha no contraturno das aulas?
Não                                    20     69.0
Sim                                     9     31.0

                                                    count  percent
Já trancou cadeiras por não acompanhar o conteúdo?
Não                                                    15     51.7
Sim                                                    14     48.3

trancou    0  1
trabalha
0         14  6
1          1  8

trancou      0     1
trabalha
0         70.0  30.0
1         11.1  88.9

#### Alunos: participa_lab × trocar_curso

In [120]:
display(freq_table(alunos, COL["al_participa_lab"]))
display(freq_table(alunos, COL["al_trocar_curso"]))

display(crosstab_counts(alunos, "participa_lab", "trocar_curso"))
display(crosstab_rowperc(alunos, "participa_lab", "trocar_curso"))

                                                    count  percent
Participa de algum laboratório ou projeto de pe...
Não                                                    18     62.1
Sim                                                    11     37.9

                            count  percent
Considera trocar de curso?
Não                            18     62.1
Sim                            11     37.9

trocar_curso    0  1
participa_lab
0              11  7
1               7  4

trocar_curso      0     1
participa_lab
0              61.1  38.9
1              63.6  36.4

#### Alunos: conhece_oport × participa_lab

In [121]:
display(freq_table(alunos, COL["al_conhece_oport"]))
display(freq_table(alunos, COL["al_participa_lab"]))

display(crosstab_counts(alunos, "conhece_oport", "participa_lab"))
display(crosstab_rowperc(alunos, "conhece_oport", "participa_lab"))

                                                    count  percent
Você conhece as oportunidades de iniciação cien...
Não                                                    11     37.9
Sim                                                    18     62.1

                                                    count  percent
Participa de algum laboratório ou projeto de pe...
Não                                                    18     62.1
Sim                                                    11     37.9

participa_lab   0  1
conhece_oport
0               7  4
1              11  7

participa_lab     0     1
conhece_oport
0              63.6  36.4
1              61.1  38.9

#### Alunos: atende_req × participa_lab

In [122]:
display(freq_table(alunos, COL["al_atende_req"]))
display(freq_table(alunos, COL["al_participa_lab"]))

display(crosstab_counts(alunos, "atende_req", "participa_lab"))
display(crosstab_rowperc(alunos, "atende_req", "participa_lab"))

                                                    count  percent
Você atende aos requisitos necessários para par...
Não                                                    16     55.2
Sim                                                    13     44.8

                                                    count  percent
Participa de algum laboratório ou projeto de pe...
Não                                                    18     62.1
Sim                                                    11     37.9

participa_lab   0  1
atende_req
0              12  4
1               6  7

participa_lab     0     1
atende_req
0              75.0  25.0
1              46.2  53.8

#### Alunos: boa_base_num × acompanha_num

In [123]:
display(freq_table(alunos, COL["al_boa_base"]))
display(freq_table(alunos, COL["al_acompanha"]))

display(crosstab_counts(alunos, "boa_base_num", "acompanha_num"))
display(crosstab_rowperc(alunos, "boa_base_num", "acompanha_num"))

                                                    count  percent
Recebi uma boa base de aprendizado durante os a...
Concordo parcialmente                                   9     31.0
Concordo totalmente                                     8     27.6
Discordo parcialmente                                   2      6.9
Discordo totalmente                                     4     13.8
Nem concordo nem discordo                               6     20.7

                                                    count  percent
Consigo acompanhar a maioria dos conteúdos mini...
Concordo parcialmente                                  11     37.9
Concordo totalmente                                     2      6.9
Discordo parcialmente                                   5     17.2
Discordo totalmente                                     5     17.2
Nem concordo nem discordo                               6     20.7

acompanha_num  1  2  3  4  5
boa_base_num
1              1  0  3  0  0
2              0  1  0  1  0
3              2  1  1  2  0
4              1  2  2  3  1
5              1  1  0  5  1

acompanha_num     1     2     3     4     5
boa_base_num
1              25.0   0.0  75.0   0.0   0.0
2               0.0  50.0   0.0  50.0   0.0
3              33.3  16.7  16.7  33.3   0.0
4              11.1  22.2  22.2  33.3  11.1
5              12.5  12.5   0.0  62.5  12.5

#### Pesquisadores: falta_tempo_num × pensou_desistir

In [124]:
display(freq_table(pesquisadores, COL["pes_falta_tempo"]))
display(freq_table(pesquisadores, COL["pes_pensou_desistir"]))

display(crosstab_counts(pesquisadores, "pensou_desistir", "falta_tempo_num"))
display(crosstab_rowperc(pesquisadores, "pensou_desistir", "falta_tempo_num"))

                                                    count  percent
Sinto que não tenho tempo suficiente para conci...
Concordo parcialmente                                  13     52.0
Concordo totalmente                                     1      4.0
Discordo parcialmente                                   7     28.0
Discordo totalmente                                     1      4.0
Nem concordo nem discordo                               3     12.0

                                                    count  percent
Já pensou em desistir da atividade de laboratór...
Não                                                    13     52.0
Sim                                                    12     48.0

falta_tempo_num  1  2  3  4  5
pensou_desistir
0                1  5  1  6  0
1                0  2  2  7  1

falta_tempo_num    1     2     3     4    5
pensou_desistir
0                7.7  38.5   7.7  46.2  0.0
1                0.0  16.7  16.7  58.3  8.3

#### Pesquisadores: orientacao_num × recomendaria

In [125]:
display(freq_table(pesquisadores, COL["pes_orientacao"]))
display(freq_table(pesquisadores, COL["pes_recomendaria"]))

display(crosstab_counts(pesquisadores, "recomendaria", "orientacao_num"))
display(crosstab_rowperc(pesquisadores, "recomendaria", "orientacao_num"))

                                                    count  percent
Recebo orientação adequada do meu professor ori...
Concordo parcialmente                                   6     24.0
Concordo totalmente                                    16     64.0
Discordo parcialmente                                   2      8.0
Nem concordo nem discordo                               1      4.0

                                                    count  percent
Você já recomendou a colegas a participação no ...
Não                                                     4     16.0
Sim                                                    21     84.0

orientacao_num  2  3  4   5
recomendaria
0               1  0  2   1
1               1  1  4  15

orientacao_num     2    3     4     5
recomendaria
0               25.0  0.0  50.0  25.0
1                4.8  4.8  19.0  71.4

#### Pesquisadores: reconhecimento_num × recomendaria

In [126]:
display(freq_table(pesquisadores, COL["pes_recomendaria"]))
display(freq_table(pesquisadores, COL["pes_reconhecimento_motiv"]))

display(crosstab_counts(pesquisadores, "recomendaria", "reconhecimento_num"))
display(crosstab_rowperc(pesquisadores, "recomendaria", "reconhecimento_num"))

                                                    count  percent
Você já recomendou a colegas a participação no ...
Não                                                     4     16.0
Sim                                                    21     84.0

                                                    count  percent
O reconhecimento (formal ou informal) pelo meu ...
Concordo parcialmente                                   7     28.0
Concordo totalmente                                    14     56.0
Discordo parcialmente                                   1      4.0
Nem concordo nem discordo                               3     12.0

reconhecimento_num  2  3  4   5
recomendaria
0                   0  2  1   1
1                   1  1  6  13

reconhecimento_num    2     3     4     5
recomendaria
0                   0.0  50.0  25.0  25.0
1                   4.8   4.8  28.6  61.9

#### Pesquisadores: participacao × pensou_desistir

In [127]:
display(freq_table(pesquisadores, COL["pes_participacao"]))
display(freq_table(pesquisadores, COL["pes_pensou_desistir"]))

display(crosstab_counts(pesquisadores, "participacao", "pensou_desistir"))
display(crosstab_rowperc(pesquisadores, "participacao", "pensou_desistir"))

                                                    count  percent
Qual a sua participação em relação às atividade...
Bolsista                                               16     64.0
Não se aplica à minha atividade                         3     12.0
Voluntário                                              6     24.0

                                                    count  percent
Já pensou em desistir da atividade de laboratór...
Não                                                    13     52.0
Sim                                                    12     48.0

pensou_desistir                   0  1
participacao
Bolsista                         11  5
Não se aplica à minha atividade   1  2
Voluntário                        1  5

pensou_desistir                     0     1
participacao
Bolsista                         68.8  31.2
Não se aplica à minha atividade  33.3  66.7
Voluntário                       16.7  83.3

#### Pesquisadores: orientacao_num × pensou_desistir

In [128]:
display(freq_table(pesquisadores, COL["pes_orientacao"]))
display(freq_table(pesquisadores, COL["pes_pensou_desistir"]))

display(crosstab_counts(pesquisadores, "orientacao_num", "pensou_desistir"))
display(crosstab_rowperc(pesquisadores, "orientacao_num", "pensou_desistir"))

                                                    count  percent
Recebo orientação adequada do meu professor ori...
Concordo parcialmente                                   6     24.0
Concordo totalmente                                    16     64.0
Discordo parcialmente                                   2      8.0
Nem concordo nem discordo                               1      4.0

                                                    count  percent
Já pensou em desistir da atividade de laboratór...
Não                                                    13     52.0
Sim                                                    12     48.0

pensou_desistir   0  1
orientacao_num
2                 1  1
3                 0  1
4                 2  4
5                10  6

pensou_desistir     0      1
orientacao_num
2                50.0   50.0
3                 0.0  100.0
4                33.3   66.7
5                62.5   37.5

#### Pesquisadores: bolsa_suficiente_num × pensou_desistir

In [129]:
display(freq_table(pesquisadores, COL["pes_bolsa_suficiente"]))
display(freq_table(pesquisadores, COL["pes_pensou_desistir"]))

display(crosstab_counts(pesquisadores, "bolsa_suficiente_num", "pensou_desistir"))
display(crosstab_rowperc(pesquisadores, "bolsa_suficiente_num", "pensou_desistir"))

                                                    count  percent
A bolsa que recebo é suficiente para cobrir min...
Concordo parcialmente                                   5     20.0
Concordo totalmente                                     5     20.0
Discordo parcialmente                                   4     16.0
Discordo totalmente                                     3     12.0
Nem concordo nem discordo                               8     32.0

                                                    count  percent
Já pensou em desistir da atividade de laboratór...
Não                                                    13     52.0
Sim                                                    12     48.0

pensou_desistir       0  1
bolsa_suficiente_num
1                     0  3
2                     1  3
3                     4  4
4                     4  1
5                     4  1

pensou_desistir          0      1
bolsa_suficiente_num
1                      0.0  100.0
2                     25.0   75.0
3                     50.0   50.0
4                     80.0   20.0
5                     80.0   20.0

#### Ponte: comparar “lab_ajuda” entre alunos e pesquisadores

In [130]:
# alunos
al_counts = alunos["lab_ajuda_num"].value_counts().sort_index()
al_perc = (al_counts / al_counts.sum() * 100).round(1)

# pesquisadores
pes_counts = pesquisadores["lab_ajuda_num"].value_counts().sort_index()
pes_perc = (pes_counts / pes_counts.sum() * 100).round(1)

pd.DataFrame({
    "alunos_count": al_counts,
    "alunos_%": al_perc,
    "pesq_count": pes_counts,
    "pesq_%": pes_perc,
}).fillna(0)

               alunos_count  alunos_%  pesq_count  pesq_%
lab_ajuda_num
1                         1       3.4         0.0     0.0
2                         1       3.4         1.0     4.0
3                         2       6.9         4.0    16.0
4                        12      41.4         9.0    36.0
5                        13      44.8        11.0    44.0